### ISSUE TITLE
Add expression support for phase

### ISSUE THREAD

**Issue by Roger-luo** [QuantumBFS/ZXCalculus.jl#1]
move `P` to `Any` will allow us to use polynomial types.

https://github.com/ChenZhao44/ZX.jl/blob/5e53461f9a4123acd27fd906e8eb6c1542d5fe19/src/zx_diagram.jl#L13

```julia
mutable struct ZXDiagram{T<:Integer, U<:Integer}
    g::Multigraph{T,U}

    st::Vector{SType}
    ps::Vector{Any}

```

**Comment by ChenZhao44** [comment]
If we want to simplify hybrid programs in YaoLang, we should handle phases with expressions.

**Comment by ChenZhao44** [comment]
It was supported by `Phase`.
