### ISSUE TITLE
How to visualize/manipulate in Julia?

### ISSUE THREAD

**Issue by ofstrings2** [QuantumBFS/ZXCalculus.jl#38]
Hello, I installed the ZXCalculus.jl package & I'm using Jupyter notebooks. Is there documentation for how to use this? Thanks!

**Comment by Roger-luo** [comment]
Hi thanks for being interested in this! We are still working on examples and documentations, but you can find some simple ones here: https://github.com/QuantumBFS/ZXCalculus.jl/blob/master/example/ex1.jl 

Regarding to plotting the diagram, it's in https://github.com/QuantumBFS/YaoPlots.jl, it's mainly written for debugging the package for now, thus not perfect yet. There is only one function you need to know about plotting which is `plot`, you can find an example in the tests: https://github.com/QuantumBFS/YaoPlots.jl/blob/master/test/runtests.jl#L18

as you might notice, this package just released it's first version weeks ago, and we are still working on it as our GSoC project this summer. We have finished implementing the clifford simplification and phase teleportation algorithm, and still working on integrating with our compiler here: https://github.com/QuantumBFS/YaoLang.jl/pull/41 

I'll be expecting to have some more detailed docs after this PR is done. Hope this helps.
But anyway, please feel free to ask your questions and discuss with us under using issue.

**Comment by ChenZhao44** [comment]
> Hello, I installed the ZXCalculus.jl package & I'm using Jupyter notebooks. Is there documentation for how to use this? Thanks!

Hi, thanks for being interested in our project. There is the documentation for ZXCalculus.jl now. Please refer to [this page](https://yaoquantum.org/ZXCalculus.jl/dev/).
The integration with `YaoLang.jl` is still developing. We will update it later.

**Comment by Roger-luo** [comment]
I'll close this, but please feel free to open other issue @ofstrings2
